### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by HX-Javier** [khellang/Hellang.MessageBus#1]
Hey, we just wanted to use this in .NET Core. Do you have any plans to make it compatible? The issue appears to be the SynchronizationContext...

**Comment by khellang** [comment]
Hey! Wow, I haven't looked at this project in ages (totally forgot it existed 😉). I can have a look to see what it would take to make it work.

**Comment by khellang** [comment]
Pushed a new version, v2.0.0, to NuGet.org. Let me know if it works 😄
